name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu]
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: refresh package inventory
      run: sudo apt update

    - name: Install libudev-dev
      run: sudo apt-get install -y libudev-dev

    - name: Build
      run: cargo build --bin TheBus2Komsi --verbose

    - name: Run tests
      run: cargo test --verbose
